[package]
name = "ast-grep-language"
version = "0.1.15"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/ast-grep/ast-grep"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast-grep-core = { version= "0.1.15", path = "../core" }
ignore = "0.4.19"
serde = { version = "1.0", features = ["derive"] }

tree-sitter-c = { version = "0.20.2", optional = true }
tree-sitter-go = { version = "0.19.1", optional = true }
tree-sitter-html = { version = "0.19.0", optional = true }
tree-sitter-java = { version = "0.20.0", optional = true }
tree-sitter-javascript = { version = "0.20.0", optional = true }
tree-sitter-kotlin = { version = "0.2.11", optional = true }
tree-sitter-lua = { version = "0.0.14", optional = true }
tree-sitter-python = { version = "0.20.2", optional = true }
tree-sitter-rust = { version = "0.20.3", optional = true }
tree-sitter-swift = { version = "0.3.4", optional = true }
tree-sitter-typescript= { version = "0.20.1", optional = true }
tree-sitter-c-sharp = { version = "0.20.0", package = "ast-grep-tree-sitter-c-sharp", optional = true }

[features]
builtin-parser = [
  "tree-sitter-c",
  "tree-sitter-go",
  "tree-sitter-html",
  "tree-sitter-java",
  "tree-sitter-javascript",
  "tree-sitter-kotlin",
  "tree-sitter-lua",
  "tree-sitter-python",
  "tree-sitter-rust",
  "tree-sitter-swift",
  "tree-sitter-typescript",
  "tree-sitter-c-sharp",
]
default = ["builtin-parser"]
