[package]
name = "ast-grep-config"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["regex"]

[dependencies]
ast-grep-core = { version= "0.5.3", path = "../core" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
regex = {version = "1.8.1", optional = true }
globset = "0.4.10"
bit-set = "0.5.3"
thiserror = "1.0.40"
anyhow = "1.0"

[dev-dependencies]
tree-sitter-typescript="0.20.2"
tempdir = "0.3"
