[package]
name = "ast-grep-dynamic"
description = "Load tree-sitter dynamic library for ast-grep"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ast-grep-core.workspace = true

ignore = "0.4.20"
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.40"
tree-sitter-native = { version = "0.20.10", package = "tree-sitter" }
