[package]
name = "ast-grep-core"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
categories = ["command-line-utilities", "development-tools", "parsing"]

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
regex = {version = "1.8.1", optional = true }
tree-sitter = { version = "0.9.1", package = "tree-sitter-facade-sg" }
bit-set = "0.5.3"
thiserror = "1.0.40"

[features]
default = ["regex"]

[dev-dependencies]
tree-sitter-typescript="0.20.2"
