[package]
name = "ast-grep-pyo3"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
edition = "2018"

authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ast_grep"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"